# 1) Import three dataset(Dognition data: test_info + dog_info + membership_info)

In [ ]:
import pandas as pd

# Understand the data structure : User -> Dog -> Test

In [ ]:
# Check duplicated values in Dog ID

                                     Dog ID  num_tests
0      fd27b272-7144-11e5-ba71-058fbc01cf0b          1
1      fd27b5ba-7144-11e5-ba71-058fbc01cf0b          1
2      fd27b6b4-7144-11e5-ba71-058fbc01cf0b          1
3      fd27b79a-7144-11e5-ba71-058fbc01cf0b          1
4      fd27b86c-7144-11e5-ba71-058fbc01cf0b          1
...                                     ...        ...
17981  fdc235e0-7144-11e5-ba71-058fbc01cf0b          1
17982  fdc23a68-7144-11e5-ba71-058fbc01cf0b          1
17983  fdc23ba8-7144-11e5-ba71-058fbc01cf0b          1
17984  fdc23e96-7144-11e5-ba71-058fbc01cf0b          1
17985  fdc2417a-7144-11e5-ba71-058fbc01cf0b          1

[17986 rows x 2 columns]

# 2) Merge three dataset together (using merge)
- consider 'inner', 'left' ,' right' , 'outer'
- check null value in 'Dog ID' or 'User ID'

,Unnamed: 0,Dog ID,User ID,Gender,Birthday,Breed,Breed_Type,Breed_Group,Weight,Dog_Fixed,DNA_Tested,Dimension,Sign_in_Count
16643,16643,fdbb6b7a-7144-11e5-ba71-058fbc01cf0b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# how many rows of total ?

17986

# 3) How many unique human user IDs are there in the aggregated data set?

16261

# 4) What feature is common to all the rows that have a value of 37 in the “State” field of the aggregated data set?

,Unnamed: 0_x,Dog ID,Total Tests Completed,Mean ITI (days),Mean ITI (minutes),Median ITI (days),Median ITI (minutes),Time diff between first and last game (days),Time diff between first and last game (minutes),Unnamed: 0_y,...,Max_Dogs,Membership_ID,Subscribed,City,State,Country,Exclude,Free_Start_User,Last_Active_At,Membership_Type
398,398,fd40fa66-7144-11e5-ba71-058fbc01cf0b,20,0.011260,16.214035,0.006331,9.116667,0.213935,308.066667,398,...,1.0,1.0,1.0,Tallinn,37,EE,0,0,6/27/14 14:45,1
5399,5399,fd674df6-7144-11e5-ba71-058fbc01cf0b,31,8.002653,11523.820000,0.004028,5.800000,240.079583,345714.600000,5399,...,1.0,3.0,1.0,Tallinn,37,EE,0,1,8/3/15 5:50,3
11208,11208,fd7c19fc-7144-11e5-ba71-058fbc01cf0b,2,0.002708,3.900000,0.002708,3.900000,0.002708,3.900000,11208,...,1.0,10.0,1.0,Tallinn,37,EE,0,0,5/9/15 8:02,1
15678,15678,fdb61558-7144-11e5-ba71-058fbc01cf0b,14,2.751638,3962.358974,0.390069,561.700000,35.771296,51510.666667,15678,...,1.0,10.0,0.0,Harju County,37,EE,0,1,9/24/15 18:15,1
15721,15721,fdb64e7e-7144-11e5-ba71-058fbc01cf0b,20,0.367163,528.714035,0.004144,5.966667,6.976088,10045.566667,15721,...,1.0,10.0,1.0,Viimsi Vald,37,EE,0,0,8/17/15 19:15,1
15724,15724,fdb653ba-7144-11e5-ba71-058fbc01cf0b,7,2.514662,3621.113889,0.011036,15.891667,15.087975,21726.683333,15724,...,2.0,10.0,0.0,Tallinn,37,EE,0,1,9/22/15 13:42,1
15737,15737,fdb67228-7144-11e5-ba71-058fbc01cf0b,7,5.146622,7411.136111,0.009502,13.683333,30.879734,44466.816667,15737,...,1.0,10.0,1.0,Tallinn,37,EE,0,0,9/13/15 16:35,1
15996,15996,fdb7e716-7144-11e5-ba71-058fbc01cf0b,20,0.472172,679.927193,0.006227,8.966667,8.971262,12918.616667,15996,...,1.0,10.0,0.0,Tallinn,37,EE,0,0,9/7/15 18:17,1
16090,16090,fdb84d78-7144-11e5-ba71-058fbc01cf0b,7,0.952029,1370.922222,0.010451,15.050000,5.712176,8225.533333,16090,...,1.0,10.0,1.0,Tallinn,37,EE,0,0,9/6/15 12:40,1
16132,16132,fdb893be-7144-11e5-ba71-058fbc01cf0b,20,0.003333,4.799123,0.002894,4.166667,0.063322,91.183333,16132,...,2.0,10.0,0.0,Tartu,37,EE,0,0,9/1/15 15:05,1
16960,16960,fdbdf868-7144-11e5-ba71-058fbc01cf0b,7,0.177894,256.166667,0.004508,6.491667,1.067361,1537.000000,16960,...,2.0,10.0,0.0,Tallinn,37,EE,0,1,9/22/15 13:42,1

# 4) What feature is common to all the rows that have a value of 'CA' in the “Membership_Type” field of the aggregated data set? 
- write your thoughts on whether you want to keep these rows or not

,Unnamed: 0_x,Dog ID,Total Tests Completed,Mean ITI (days),Mean ITI (minutes),Median ITI (days),Median ITI (minutes),Time diff between first and last game (days),Time diff between first and last game (minutes),Unnamed: 0_y,...,Max_Dogs,Membership_ID,Subscribed,City,State,Country,Exclude,Free_Start_User,Last_Active_At,Membership_Type
313,313,fd4060f6-7144-11e5-ba71-058fbc01cf0b,20,0.219882,316.630702,0.001875,2.700000,4.177766,6015.983333,313,...,2.0,2.0,0.0,Thornhill,ON,CA,l4j,Thornhill West,ON,CA
383,383,fd40e206-7144-11e5-ba71-058fbc01cf0b,13,29.552486,42555.579167,0.001418,2.041667,354.629826,510666.950000,383,...,6.0,2.0,1.0,Nepean East,ON,CA,K2E,Nepean East,ON,CA
712,712,fd4277a6-7144-11e5-ba71-058fbc01cf0b,2,0.001424,2.050000,0.001424,2.050000,0.001424,2.050000,712,...,6.0,2.0,1.0,Nepean East,ON,CA,K2E,Nepean East,ON,CA
1471,1471,fd454daa-7144-11e5-ba71-058fbc01cf0b,6,63.783586,91848.363333,0.017650,25.416667,318.917928,459241.816667,1471,...,1.0,2.0,1.0,Bowen Island,BC,CA,V0N,North Island,BC,CA
1505,1505,fd456290-7144-11e5-ba71-058fbc01cf0b,20,0.258433,372.142982,0.003183,4.583333,4.910220,7070.716667,1505,...,1.0,1.0,1.0,Quinte Shores,ON,CA,K0k,Quinte Shores,ON,CA
3163,3163,fd51c256-7144-11e5-ba71-058fbc01cf0b,10,14.117831,20329.675926,0.005301,7.633333,127.060475,182967.083333,3163,...,1.0,1.0,1.0,Pender Island,BC,CA,V0N,North Island,BC,CA
4682,4682,fd641f82-7144-11e5-ba71-058fbc01cf0b,16,0.459559,661.764444,0.005787,8.333333,6.893380,9926.466667,4682,...,1.0,1.0,0.0,Bowen Island,BC,CA,v0n,North Island,BC,CA
6252,6252,fd6a596a-7144-11e5-ba71-058fbc01cf0b,6,2.598900,3742.416667,0.006794,9.783333,12.994502,18712.083333,6252,...,1.0,10.0,1.0,Whitby,ON,CA,L1N,Whitby Southeast,ON,CA
6331,6331,fd6aa294-7144-11e5-ba71-058fbc01cf0b,7,0.007442,10.716667,0.004537,6.533333,0.044653,64.300000,6331,...,1.0,10.0,1.0,Richmond Hill,ON,CA,L4C,Richmond Hill Southwest,ON,CA
6338,6338,fd6aa550-7144-11e5-ba71-058fbc01cf0b,4,3.676327,5293.911111,0.176389,254.000000,11.028981,15881.733333,6338,...,1.0,10.0,1.0,Mississauga,ON,CA,L5B,Mississauga (West Cooksville / Fairview / City...,ON,CA
6352,6352,fd6aab18-7144-11e5-ba71-058fbc01cf0b,20,0.480562,692.008772,0.005810,8.366667,9.130671,13148.166667,6352,...,1.0,10.0,1.0,London,ON,CA,N6p,London (Talbot / Lambeth / West Tempo / South ...,ON,CA
6419,6419,fd6ad58e-7144-11e5-ba71-058fbc01cf0b,7,0.152276,219.277778,0.004497,6.475000,0.913657,1315.666667,6419,...,1.0,10.0,1.0,Toronto,ON,CA,M5A,Downtown Toronto (Regent Park / Port of Toronto),ON,CA
6445,6445,fd6ae862-7144-11e5-ba71-058fbc01cf0b,20,1.472448,2120.324561,0.004792,6.900000,27.976505,40286.166667,6445,...,1.0,10.0,1.0,Guelph,ON,CA,N1H,Guelph Northwest,ON,CA
6464,6464,fd6bd66e-7144-11e5-ba71-058fbc01cf0b,11,31.201326,44929.910000,0.003848,5.541667,312.013264,449299.100000,6464,...,1.0,11.0,1.0,Toronto,ON,CA,M5a,Downtown Toronto (Regent Park / Port of Toronto),ON,CA
6490,6490,fd6be9ec-7144-11e5-ba71-058fbc01cf0b,20,0.401698,578.444737,0.004583,6.600000,7.632257,10990.450000,6490,...,1.0,10.0,1.0,Toronto,ON,CA,M4E,East Toronto (The Beaches),ON,CA
6565,6565,fd6c288a-7144-11e5-ba71-058fbc01cf0b,6,3.397757,4892.770000,0.007106,10.233333,16.988785,24463.850000,6565,...,1.0,10.0,0.0,Toronto,ON,CA,M6K,West Toronto (Brockton / Parkdale Village / Ex...,ON,CA
6592,6592,fd6c6796-7144-11e5-ba71-058fbc01cf0b,4,0.002901,4.177778,0.002685,3.866667,0.008704,12.533333,6592,...,1.0,10.0,1.0,Victoria,BC,CA,V8T,Victoria North,BC,CA
6621,6621,fd6c7bfa-7144-11e5-ba71-058fbc01cf0b,7,10.018681,14426.900000,0.005394,7.766667,60.112083,86561.400000,6621,...,1.0,10.0,1.0,Vancouver,BC,CA,V6B,Vancouver (NE Downtown / Harbour Centre / Gast...,BC,CA
6661,6661,fd6ca486-7144-11e5-ba71-058fbc01cf0b,20,0.738658,1063.667544,0.010926,15.733333,14.034502,20209.683333,6661,...,1.0,10.0,1.0,Vancouver,BC,CA,V6K,Vancouver (Central Kitsilano),BC,CA
6772,6772,fd6d1a56-7144-11e5-ba71-058fbc01cf0b,16,0.268525,386.675556,0.004410,6.350000,4.027870,5800.133333,6772,...,1.0,10.0,0.0,Pembroke,ON,CA,K8A,Pembroke Central and northern subdivisions,ON,CA
6796,6796,fd6d2780-7144-11e5-ba71-058fbc01cf0b,4,1.051856,1514.672222,0.008912,12.833333,3.155567,4544.016667,6796,...,2.0,11.0,1.0,Ahuntsic Southwest,QC,CA,H3L,Ahuntsic Southwest,QC,CA
6883,6883,fd6d7910-7144-11e5-ba71-058fbc01cf0b,11,0.092846,133.698333,0.002934,4.225000,0.928461,1336.983333,6883,...,1.0,10.0,1.0,Guelph,ON,CA,N1E,Guelph North,ON,CA
6929,6929,fd6d9792-7144-11e5-ba71-058fbc01cf0b,13,0.250557,360.801389,0.004473,6.441667,3.006678,4329.616667,6929,...,1.0,10.0,1.0,Scarborough,ON,CA,m1e,Scarborough (Guildwood / Morningside / Ellesmere),ON,CA
6934,6934,fd6da002-7144-11e5-ba71-058fbc01cf0b,7,0.166998,240.477778,0.003698,5.325000,1.001991,1442.866667,6934,...,1.0,10.0,1.0,Grimsby,ON,CA,L3M,Grimsby,ON,CA
6947,6947,fd6dbd76-7144-11e5-ba71-058fbc01cf0b,6,0.005863,8.443333,0.004595,6.616667,0.029317,42.216667,6947,...,1.0,10.0,1.0,South Okanagan (summerland),BC,CA,V0H,South Okanagan (Summerland),BC,CA
6949,6949,fd6dbf42-7144-11e5-ba71-058fbc01cf0b,16,0.149086,214.683333,0.002755,3.966667,2.236285,3220.250000,6949,...,1.0,10.0,0.0,North Bay,ON,CA,P1B,North Bay Central,ON,CA
6967,6967,fd6dc938-7144-11e5-ba71-058fbc01cf0b,13,11.924569,17171.379167,0.004740,6.825000,143.094826,206056.550000,6967,...,1.0,10.0,1.0,Burlington,ON,CA,L7S,Burlington South,ON,CA
7003,7003,fd6de18e-7144-11e5-ba71-058fbc01cf0b,4,0.004024,5.794444,0.002199,3.166667,0.012072,17.383333,7003,...,1.0,10.0,1.0,Ancaster,ON,CA,L9G,Ancaster West,ON,CA
7045,7045,fd6df818-7144-11e5-ba71-058fbc01cf0b,7,0.842033,1212.527778,0.005434,7.825000,5.052199,7275.166667,7045,...,1.0,10.0,1.0,Georgian Bay Southwest Shore (dundalk),ON,CA,N0C,Georgian Bay Southwest Shore (Dundalk),ON,CA
7092,7092,fd6e2bd0-7144-11e5-ba71-058fbc01cf0b,16,0.337824,486.466667,0.004352,6.266667,5.067361,7297.000000,7092,...,1.0,10.0,1.0,Harrietsfield,NS,CA,B3V,Harrietsfield,NS,CA
7120,7120,fd6e3ba2-7144-11e5-ba71-058fbc01cf0b,16,0.202061,290.967778,0.004780,6.883333,3.030914,4364.516667,7120,...,2.0,10.0,1.0,Outaouais-sud (thurso),QC,CA,J0X,Outaouais-Sud (Thurso),QC,CA
7138,7138,fd6e462e-7144-11e5-ba71-058fbc01cf0b,14,0.004470,6.437179,0.002940,4.233333,0.058113,83.683333,7138,...,1.0,10.0,1.0,Stouffville,ON,CA,L4A,Stouffville,ON,CA
7179,7179,fd6e5b14-7144-11e5-ba71-058fbc01cf0b,6,0.004176,6.013333,0.003472,5.000000,0.020880,30.066667,7179,...,1.0,10.0,1.0,Toronto,ON,CA,M6s,West Toronto (Bloor West Village / Swansea),ON,CA
7289,7289,fd6eb0aa-7144-11e5-ba71-058fbc01cf0b,20,1.479202,2130.050877,0.004514,6.500000,28.104838,40470.966667,7289,...,1.0,11.0,0.0,Vancouver,BC,CA,V6N,Vancouver (Dunbar- Southlands / Musqueam),BC,CA
7845,7845,fd706166-7144-11e5-ba71-058fbc01cf0b,7,0.169986,244.780556,0.005932,8.541667,1.019919,1468.683333,7845,...,1.0,10.0,1.0,Oak Bay North,BC,CA,v8r,Oak Bay North,BC,CA
8116,8116,fd713a8c-7144-11e5-ba71-058fbc01cf0b,4,0.004097,5.900000,0.003345,4.816667,0.012292,17.700000,8116,...,1.0,10.0,1.0,Galiano Island,BC,CA,V0N,North Island,BC,CA
8313,8313,fd71c33a-7144-11e5-ba71-058fbc01cf0b,11,0.199689,287.551667,0.004537,6.533333,1.996887,2875.516667,8313,...,1.0,10.0,0.0,St. John's,NL,CA,A1B,St. John's Northwest Newfoundland & Labrador P...,NL,CA
9402,9402,fd75031a-7144-11e5-ba71-058fbc01cf0b,20,6.319902,9100.658772,0.004178,6.016667,120.078137,172912.516667,9402,...,1.0,10.0,1.0,Whitby,ON,CA,L1M,Whitby North,ON,CA
9645,9645,fd764b44-7144-11e5-ba71-058fbc01cf0b,1,NaN,NaN,NaN,NaN,0.000000,0.000000,9645,...,1.0,10.0,1.0,Vancouver,BC,CA,V6K,Vancouver (Central Kitsilano),BC,CA
13272,13272,fdab1d10-7144-11e5-ba71-058fbc01cf0b,11,0.905472,1303.880000,0.004346,6.258333,9.054722,13038.800000,13272,...,1.0,10.0,1.0,Oakville,ON,CA,L6M,Oakville West,ON,CA

# 5) Can people have more than 100 dogs? or Sign_in_Count more than 175 ?

User ID
ce7b75bc-7144-11e5-ba71-058fbc01cf0b    502
ce225842-7144-11e5-ba71-058fbc01cf0b     17
ce2258a6-7144-11e5-ba71-058fbc01cf0b     16
ce135e14-7144-11e5-ba71-058fbc01cf0b     10
ce29675e-7144-11e5-ba71-058fbc01cf0b     10
                                       ...
ce672206-7144-11e5-ba71-058fbc01cf0b      1
ce6729ea-7144-11e5-ba71-058fbc01cf0b      1
ce672ac6-7144-11e5-ba71-058fbc01cf0b      1
ce672b84-7144-11e5-ba71-058fbc01cf0b      1
ce9b35e6-7144-11e5-ba71-058fbc01cf0b      1
Name: Dog ID, Length: 16261, dtype: int64

Sign_in_Count
1489.0    17
1695.0    16
181.0     10
355.0      4
594.0      2
310.0      1
Name: count, dtype: int64

# 6) what personality type has the strongest representation (greatest number of records) in the sporting breed group?

Dimension
0                  1908
socialite           195
charmer             128
protodog             92
ace                  73
renaissance-dog      67
stargazer            48
expert               42
maverick             20
einstein             14
Name: count, dtype: int64

# 7) How many U.S states did customers complete a median number of tests that was greater than 13?
- think about the difference between median and average. which one is more sensitive to extreme values?

State
AK    15.0
AP    13.5
GU    20.0
IA    15.0
ME    18.0
NC    14.0
ND    19.5
SD    20.0
WY    15.0
Name: Total Tests Completed, dtype: float64